### ISSUE TITLE
Todo list for refactoring.

### ISSUE THREAD

**Issue by rudzainy** [rudzainy/ranting#21]
- [x] Re-organize views file structures
  - [x]  `views > dashboard` -> `views > analytics`
  - [x]  `links > show` -> `users > show`
  - [x] `views > dashboard > design` -> `users > edit`
  - [x] `views > dashboard > index` -> `links > index`
