### ISSUE TITLE
Todo Features for launch.

### ISSUE THREAD

**Issue by rudzainy** [rudzainy/ranting#22]
### Die die must have

- [x] analytics
  - [x] profile page view count
  - [x] link clicks count
  - [x] unique profile page view & link clicks count (TBD)
- [x] links
  - [x] Standard 5 external links
  - [x] Popular social media links
    - [x] https://www.facebook.com/
    - [x] https://twitter.com/
    - [x] https://www.youtube.com/
    - [x] https://www.instagram.com/
  - [x] image in links
- [x] users
  - [x] background colour

### Nice to haves
- [ ] links
    - [ ] integration
      - [ ] [Whatsapp](https://faq.whatsapp.com/5913398998672934) 
      - [ ] [Telegram](https://telegram.org/faq?setln=uz#q-how-does-t-me-work)

- [ ] users
  - [ ] background image
  - [ ] location
